import synthesisTraits from "@/assets/synthesis-traits.json";
import { SynthesisSearchResponse, SynthesisStatus } from "@/types";
import { getTraitsBundle } from "@/utils";
import { invoke } from "@tauri-apps/api";
import { useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";

/** The traits that appear on synthesizable sigils — the only possible
 * synthesis inputs/results, and so the only ones the dropdowns offer.
 * Generated by scripts/gen-synthesis-excluded-sigils.py. */
const SYNTHESIS_TRAITS = new Set<string>(synthesisTraits);

export type SynthesisForm = {
  /** Trait ids as 8-hex strings (the `traits:` bundle key space), or null. */
  trait1: string | null;
  trait2: string | null;
  anyOrder: boolean;
  requireLucky: boolean;
};

export type SynthesisQueryPayload = {
  trait1: number;
  trait2: number | null;
  anyOrder: boolean;
  requireLucky: boolean;
};

/** The traits people search for most, leading the picker in this order:
 * Stun Power, HP, Supplementary DMG, DMG Cap, Nimble Onslaught, Uplift. */
const POPULAR_TRAITS = ["ceb700ee", "f372f096", "57ab5b10", "dc584f60", "d2c8e10a", "b5ff9fd3"];

export type TraitOption = { value: string; label: string };
export type TraitOptions = (TraitOption | { group: string; items: TraitOption[] })[];

/** Traits bundle -> select options for synthesizable traits only: the
 * popular picks first (fixed order), then everything else alphabetically
 * inside a whitespace-labelled group — Mantine renders that label as a bare
 * divider line, which is all we want between the two blocks. */
export const buildTraitOptions = (bundle: Record<string, { text?: string }>): TraitOptions => {
  const option = (hex: string) => ({ value: hex, label: bundle[hex]?.text as string });
  const available = (hex: string) => Boolean(bundle[hex]?.text) && SYNTHESIS_TRAITS.has(hex);
  const popular = POPULAR_TRAITS.filter(available).map(option);
  const rest = Object.keys(bundle)
    .filter((hex) => available(hex) && !POPULAR_TRAITS.includes(hex))
    .map(option)
    .sort((a, b) => a.label.localeCompare(b.label));
  return [...popular, { group: " ", items: rest }];
};

/** Fresh form state: lvl-15-only results, exact slot order. */
export const initialForm: SynthesisForm = {
  trait1: null,
  trait2: null,
  anyOrder: false,
  requireLucky: true,
};

/** Form -> backend query; null when the form is incomplete (no first trait). */
export const buildQuery = (form: SynthesisForm): SynthesisQueryPayload | null => {
  if (!form.trait1) return null;
  return {
    trait1: parseInt(form.trait1, 16),
    trait2: form.trait2 ? parseInt(form.trait2, 16) : null,
    anyOrder: form.anyOrder,
    requireLucky: form.requireLucky,
  };
};

/**
 * State + handlers for the Synthesis Helper tool: a trait-pair query form,
 * the live game status, and the search results.
 */
export default function useSynthesisHelper() {
  // Re-render when the traits bundle loads / language changes (same pattern
  // as useChecklistSettings).
  const { i18n } = useTranslation("traits");
  const [form, setForm] = useState<SynthesisForm>(initialForm);
  const [status, setStatus] = useState<SynthesisStatus | null>(null);
  const [response, setResponse] = useState<SynthesisSearchResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [searching, setSearching] = useState(false);

  useEffect(() => {
    invoke<SynthesisStatus>("fetch_synthesis_status")
      .then(setStatus)
      .catch((e) => setError(String(e)));
  }, []);

  const traitOptions = useMemo(() => buildTraitOptions(getTraitsBundle()), [i18n.language]);

  const search = async () => {
    const query = buildQuery(form);
    if (!query) return;
    setSearching(true);
    setError(null);
    try {
      setResponse(await invoke<SynthesisSearchResponse>("search_synthesis", { query }));
    } catch (e) {
      setResponse(null);
      setError(String(e));
    } finally {
      setSearching(false);
    }
  };

  return { form, setForm, status, response, error, searching, traitOptions, search };
}
