//! The five effects the perfect-summon report counts — user-scoped 2026-07-30.
//!
//! [`Rule::SummonPerfectCount`] asks: did this player land top-of-ladder rolls
//! too many times over? That question is only interesting about the stats a
//! player would REROLL for. A maxed Health Up or Critical Hit Rate Up is a
//! coincidence nobody chased, and counting it turned an ordinary endgame set
//! into a report.
//!
//! So the scope is the three families the user named: Attack Power Up, Stun
//! Power Up, and Damage Cap Up. The last is a family rather than one name —
//! Normal Attack, Skill and Skybound Art each have their own — while *Healing*
//! Cap Up is deliberately outside it. It is a cap, but not a damage one, and it
//! is the single clearest example of a maxed stat nobody rerolls for.
//!
//! # Why a name and not an id list
//!
//! Summon equip-bonus ids carry no category of their own; the effect a bonus
//! grants is known only by the name the lang file spells for it, so the name is
//! the only join available. (The overmastery report used to share this scope
//! and this module. It now counts three specific ids instead — see
//! [`super::overmastery_rules`] — because its ladder table carries a category
//! per id and it needs no lang join at all.)
//!
//! Names come from autogenerated lang files that a game update overwrites
//! (see CLAUDE.md), which is the same fragility `summons::allowed_mains` and
//! [`super::summon_bonus_values::Bonus::effect`] already carry — and it gets
//! the same treatment: a drift guard pinning the exact count of effects that
//! match, so a regeneration that re-spells "Damage Cap Up" fails here instead
//! of silently switching the report off.

/// Whether an effect is one of the five the perfect-summon report counts.
///
/// Matched on the English display name — see the module docs for why that is
/// the join and what guards it.
pub fn is_chased(effect: &str) -> bool {
    effect == "Attack Power Up" || effect == "Stun Power Up" || effect.ends_with("Damage Cap Up")
}

#[cfg(test)]
mod tests {
    use super::*;

    use crate::legality::summon_bonus_values::bonus_table;

    /// The five names, and the near-misses that make the scope worth stating.
    /// "Skill Damage Up" and "Skill Damage Cap Up" differ by one word and share
    /// a ladder, so a substring match would have swept both in.
    #[test]
    fn the_scope_is_the_five_chased_effects_and_nothing_adjacent() {
        for chased in [
            "Attack Power Up",
            "Stun Power Up",
            "Normal Attack Damage Cap Up",
            "Skill Damage Cap Up",
            "Skybound Art Damage Cap Up",
        ] {
            assert!(is_chased(chased), "{chased} should be counted");
        }

        for ignored in [
            "Healing Cap Up",
            "Health Up",
            "Critical Hit Rate Up",
            "Chain Burst Damage Up",
            "Skill Damage Up",
            "Skybound Art Damage Up",
        ] {
            assert!(!is_chased(ignored), "{ignored} should not be counted");
        }
    }

    /// THE LANG-DRIFT GUARD.
    ///
    /// The names are read from an autogenerated file a game update overwrites.
    /// If a regeneration re-spells them, every bonus stops matching and the
    /// perfect-summon report silently never fires again — a rule switched off
    /// with nothing to notice it. So pin the join: 11 effects, of which exactly
    /// the five chased names must resolve.
    #[test]
    fn the_summon_bonus_namespace_spells_the_same_five_effects() {
        let mut chased: std::collections::BTreeSet<&str> = Default::default();
        let mut all: std::collections::BTreeSet<&str> = Default::default();
        for bonus in bonus_table().values() {
            all.insert(bonus.effect.as_str());
            if is_chased(&bonus.effect) {
                chased.insert(bonus.effect.as_str());
            }
        }

        assert_eq!(all.len(), 11, "expected 11 distinct summon bonus effects");
        assert_eq!(
            chased.into_iter().collect::<Vec<_>>(),
            [
                "Attack Power Up",
                "Normal Attack Damage Cap Up",
                "Skill Damage Cap Up",
                "Skybound Art Damage Cap Up",
                "Stun Power Up",
            ],
            "the chased summon-bonus effects changed spelling — the \
             perfect-summon report is now scoped to something else"
        );
    }
}

