//! The five effects the "perfect roll" reports count — user-scoped 2026-07-30.
//!
//! Both perfection reports ([`Rule::OvermasteryAllMaxed`] and
//! [`Rule::SummonPerfectCount`]) ask the same question: did this player land
//! top-of-ladder rolls too many times over? That question is only interesting
//! about the stats a player would REROLL for. A maxed Health Up or Critical Hit
//! Rate Up is a coincidence nobody chased, and counting it turned an ordinary
//! endgame set into a report — the production case being a real four-maxed
//! overmastery set of which only two slots were stats anyone farms.
//!
//! So the scope is the three families the user named: Attack Power Up, Stun
//! Power Up, and Damage Cap Up. The last is a family rather than one name —
//! Normal Attack, Skill and Skybound Art each have their own — while *Healing*
//! Cap Up is deliberately outside it. It is a cap, but not a damage one, and it
//! is the single clearest example of a maxed stat nobody rerolls for.
//!
//! # Why a name and not an id list
//!
//! The same five effects exist in two disjoint id namespaces: overmastery ids
//! (23 ids, 11 effects) and summon equip-bonus ids (22 ids, the same 11
//! effects). Both namespaces spell them identically in `lang/en`, so one name
//! predicate scopes both rules and cannot drift apart between them.
//!
//! Names come from autogenerated lang files that a game update overwrites
//! (see CLAUDE.md), which is the same fragility `summons::allowed_mains` and
//! [`super::summon_bonus_values::Bonus::effect`] already carry — and it gets
//! the same treatment: a drift guard per namespace, pinning the exact count of
//! effects that match, so a regeneration that re-spells "Damage Cap Up" fails
//! here instead of silently switching both reports off.

use std::collections::HashMap;

use serde::Deserialize;

use super::parse_hex;

/// Whether an effect is one of the five the perfection reports count.
///
/// Matched on the English display name — see the module docs for why that is
/// the join and what guards it.
pub fn is_chased(effect: &str) -> bool {
    effect == "Attack Power Up" || effect == "Stun Power Up" || effect.ends_with("Damage Cap Up")
}

/// One row of `lang/en/overmasteries.json`, read only for its display name.
#[derive(Debug, Clone, Deserialize)]
struct RawName {
    text: String,
}

/// Overmastery display names by id.
///
/// The overmastery tables themselves carry only ladders, so unlike the summon
/// side there is no existing id-to-effect map to borrow — this is it.
fn overmastery_names() -> &'static HashMap<u32, String> {
    static NAMES: std::sync::OnceLock<HashMap<u32, String>> = std::sync::OnceLock::new();
    NAMES.get_or_init(|| {
        let names: HashMap<String, RawName> =
            serde_json::from_str(include_str!("../../lang/en/overmasteries.json"))
                .expect("overmasteries.json matches the lang shape");

        names
            .into_iter()
            .filter_map(|(key, raw)| Some((parse_hex(&key)?, raw.text)))
            .collect()
    })
}

/// Whether this overmastery id is one of the counted effects.
///
/// `false` for an id the lang file does not name: an effect that cannot be
/// identified is not one that has been shown to be chased, and the report this
/// feeds must fail closed.
pub fn overmastery_is_chased(id: u32) -> bool {
    overmastery_names()
        .get(&id)
        .is_some_and(|name| is_chased(name))
}

#[cfg(test)]
mod tests {
    use super::*;

    use crate::legality::summon_bonus_values::bonus_table;
    use crate::overmastery::stock_tables;

    /// The five names, and the near-misses that make the scope worth stating.
    /// "Skill Damage Up" and "Skill Damage Cap Up" differ by one word and share
    /// a ladder, so a substring match would have swept both in.
    #[test]
    fn the_scope_is_the_five_chased_effects_and_nothing_adjacent() {
        for chased in [
            "Attack Power Up",
            "Stun Power Up",
            "Normal Attack Damage Cap Up",
            "Skill Damage Cap Up",
            "Skybound Art Damage Cap Up",
        ] {
            assert!(is_chased(chased), "{chased} should be counted");
        }

        for ignored in [
            "Healing Cap Up",
            "Health Up",
            "Critical Hit Rate Up",
            "Chain Burst Damage Up",
            "Skill Damage Up",
            "Skybound Art Damage Up",
        ] {
            assert!(!is_chased(ignored), "{ignored} should not be counted");
        }
    }

    /// THE LANG-DRIFT GUARD, overmastery side.
    ///
    /// The names are read from an autogenerated file a game update overwrites.
    /// If a regeneration re-spells them, every id stops matching and the
    /// all-maxed report silently never fires again — a rule switched off with
    /// nothing to notice it. So pin the join: 23 ids over 11 effects, of which
    /// exactly the five chased names must resolve.
    #[test]
    fn every_overmastery_id_resolves_and_five_effects_are_chased() {
        let names = overmastery_names();
        let ids: Vec<u32> = stock_tables().params.keys().copied().collect();
        assert_eq!(ids.len(), 23, "the overmastery ladder table lost rows");

        let mut chased: std::collections::BTreeSet<&str> = Default::default();
        let mut all: std::collections::BTreeSet<&str> = Default::default();
        for id in ids {
            let name = names
                .get(&id)
                .unwrap_or_else(|| panic!("overmastery {id:08x} is unnamed in lang/en"))
                .as_str();
            all.insert(name);
            if is_chased(name) {
                chased.insert(name);
            }
        }

        assert_eq!(all.len(), 11, "expected 11 distinct overmastery effects");
        assert_eq!(
            chased.into_iter().collect::<Vec<_>>(),
            [
                "Attack Power Up",
                "Normal Attack Damage Cap Up",
                "Skill Damage Cap Up",
                "Skybound Art Damage Cap Up",
                "Stun Power Up",
            ],
            "the chased overmastery effects changed spelling — the all-maxed \
             report is now scoped to something other than what was asked for"
        );
    }

    /// THE LANG-DRIFT GUARD, summon-bonus side. Same failure mode, same pin —
    /// and it proves the two namespaces really do spell these five identically,
    /// which is what lets one predicate scope both reports.
    #[test]
    fn the_summon_bonus_namespace_spells_the_same_five_effects() {
        let mut chased: std::collections::BTreeSet<&str> = Default::default();
        let mut all: std::collections::BTreeSet<&str> = Default::default();
        for bonus in bonus_table().values() {
            all.insert(bonus.effect.as_str());
            if is_chased(&bonus.effect) {
                chased.insert(bonus.effect.as_str());
            }
        }

        assert_eq!(all.len(), 11, "expected 11 distinct summon bonus effects");
        assert_eq!(
            chased.into_iter().collect::<Vec<_>>(),
            [
                "Attack Power Up",
                "Normal Attack Damage Cap Up",
                "Skill Damage Cap Up",
                "Skybound Art Damage Cap Up",
                "Stun Power Up",
            ],
            "the chased summon-bonus effects changed spelling — the \
             perfect-summon report is now scoped to something else"
        );
    }

    /// An id no lang file names cannot be shown to be chased, so it is not
    /// counted. The report fails closed on missing data, as every rule here does.
    #[test]
    fn an_unnamed_overmastery_id_is_never_chased() {
        assert!(!overmastery_is_chased(0xdead_beef));
    }
}
