/** The bridge from the ids the damage hook reports to the hashes the
 * autogenerated lang files are keyed by. Generated by
 * `scripts/gen-skill-name-sources.mjs` into
 * `src-tauri/assets/skill-name-sources.json`.
 *
 * ui.json keys skill rows by ACTION ID; abilities.json keys them by ABILITY
 * HASH. Nothing else connects the two, so without this map a translated ability
 * name can only reach the meter by being copied into ui.json by hand — which is
 * why the six languages that ship no ui.json used to read English.
 *
 * Deliberately free of Tauri imports: the asset loader
 * (`src/assets/skill-name-sources.ts`) does the top-level `await` and calls
 * `setSkillNameSources`, so `utils.ts` — and every test that touches it — stays
 * clear of `@tauri-apps/api`.
 */

export type SkillNameNamespace = "abilities" | "summons" | "enemies";

export type SkillNameSource = {
  ns: SkillNameNamespace;
  hash: string;
  key: string;
  /** How the generator resolved this entry, on summon classes only.
   *
   * `"id"` means the body-class hash equals XXHash32Custom of the mapped
   * `So####` id — the entry is the summon it claims to be. `"name"` means no id
   * hashed to the class, so it fell back to matching the display name; those two
   * entries (the Cat and Lilith bodies) are the ones to re-check after a patch.
   * Unused at runtime; carried for auditability. */
  via?: "id" | "name";
};

export type SkillNameSources = {
  [block: string]: { [id: string]: SkillNameSource };
};

/** Tier suffix on summon names. The ASCII form requires leading whitespace so a
 * name genuinely ending in "I" survives; the full-width form (zh-CN ships
 * "黑龙伊弗欧Ⅲ") carries no space. Mirrored in
 * scripts/gen-skill-name-sources.mjs — keep both in step; the two test suites
 * share fixtures to catch drift. */
const TIER_SUFFIX = /(?:\s+I{1,3}|[Ⅰ-Ⅲ])$/;

const normalize = (text: string): string => text.replace(/\s+/g, " ").trim();

export const stripTierSuffix = (text: string): string => normalize(normalize(text).replace(TIER_SUFFIX, ""));

let sources: SkillNameSources = {};

export const setSkillNameSources = (next: SkillNameSources): void => {
  sources = next;
};

export const getSkillNameSources = (): SkillNameSources => sources;

/** i18next keys for a mapped action id, the child character's block first.
 *
 * Returns an array so callers can splice it straight into an existing `t()`
 * fallback chain: empty means "nothing mapped, carry on".
 */
export const abilitySourceKeys = (characterType: string, childCharacterType: string, skillId: number): string[] => {
  const id = String(skillId);

  for (const block of [childCharacterType, characterType]) {
    const source = sources[block]?.[id];
    if (source !== undefined) return [`${source.ns}:${source.hash}.text`];
  }

  return [];
};

export const SUMMON_CLASSES_BLOCK = "summon-classes";

export const summonClassSource = (bodyClassHash: string): SkillNameSource | null =>
  sources[SUMMON_CLASSES_BLOCK]?.[bodyClassHash] ?? null;
