/** The bridge from the ids the damage hook reports to the hashes the
 * autogenerated lang files are keyed by. Generated by
 * `scripts/gen-skill-name-sources.mjs` into
 * `src-tauri/assets/skill-name-sources.json`.
 *
 * ui.json keys skill rows by ACTION ID; abilities.json keys them by ABILITY
 * HASH. Nothing else connects the two, so without this map a translated ability
 * name can only reach the meter by being copied into ui.json by hand — which is
 * why the six languages that ship no ui.json used to read English. The map may
 * cover an action a ui.json also labels: `resolveSkillName` orders the two per
 * LANGUAGE (own label, own bridge name, then the fallback language's), so the
 * label wins inside its language without shadowing another language's name.
 *
 * Deliberately free of Tauri imports: the asset loader
 * (`src/assets/skill-name-sources.ts`) does the top-level `await` and calls
 * `setSkillNameSources`, so `utils.ts` — and every test that touches it — stays
 * clear of `@tauri-apps/api`.
 */

import i18next from "i18next";

export type SkillNameNamespace = "abilities" | "summons" | "enemies";

export type SkillNameSource = {
  ns: SkillNameNamespace;
  hash: string;
  key: string;
  /** How the generator resolved this entry, on summon classes only.
   *
   * `"id"` means the body-class hash equals XXHash32Custom of the mapped
   * `So####` id — the entry is the summon it claims to be. `"name"` means no id
   * hashed to the class, so it fell back to matching the display name; those two
   * entries (the Cat and Lilith bodies) are the ones to re-check after a patch.
   * Unused at runtime; carried for auditability. */
  via?: "id" | "name";
};

export type SkillNameSources = {
  [block: string]: { [id: string]: SkillNameSource };
};

/** Tier suffix on summon names. The ASCII form requires leading whitespace so a
 * name genuinely ending in "I" survives; the full-width form (zh-CN ships
 * "黑龙伊弗欧Ⅲ") carries no space. Mirrored in
 * scripts/gen-skill-name-sources.mjs — keep both in step; the two test suites
 * share fixtures to catch drift. */
const TIER_SUFFIX = /(?:\s+I{1,3}|[Ⅰ-Ⅲ])$/;

const normalize = (text: string): string => text.replace(/\s+/g, " ").trim();

export const stripTierSuffix = (text: string): string => normalize(normalize(text).replace(TIER_SUFFIX, ""));

let sources: SkillNameSources = {};

export const setSkillNameSources = (next: SkillNameSources): void => {
  sources = next;
};

export const getSkillNameSources = (): SkillNameSources => sources;

/** Display name for an action id, resolved language-major.
 *
 * Priority is per LANGUAGE first, source second: the current language's ui.json
 * hand label, then its bridge (game) name, and only then the fallback
 * language's label and bridge. A plain `t()` fallback array cannot express
 * this — i18next resolves each key across every language before trying the
 * next key, which would let an English-only hand label shadow a perfectly
 * translated game name. Within one language a hand label still wins (it is
 * often more specific than the game's own name), and the caller's block order
 * (child character first) is preserved.
 *
 * `i18next.languages` is the resolve hierarchy — e.g. ["fr-FR", "fr", "en"] —
 * so a regional UI language reaches its base-language bundles, and zh-TW its
 * zh-CN hop, without special cases. Each step pins ONE chain entry via `lngs`;
 * `fallbackLng: false` cannot do this — i18next treats it as falsy and swaps
 * the global fallback back in, which is exactly the leak being prevented.
 */
export const resolveSkillName = (blocks: string[], skillId: number): string | null => {
  const id = String(skillId);

  for (const lng of i18next.languages ?? []) {
    for (const block of blocks) {
      const label = i18next.t(`skills.${block}.${id}`, { lngs: [lng], defaultValue: "" });
      if (label !== "") return label;
    }

    for (const block of blocks) {
      const source = sources[block]?.[id];
      if (source === undefined) continue;

      const text = i18next.t(`${source.ns}:${source.hash}.text`, { lngs: [lng], defaultValue: "" });
      if (text !== "") return text;
    }
  }

  return null;
};

export const SUMMON_CLASSES_BLOCK = "summon-classes";

export const summonClassSource = (bodyClassHash: string): SkillNameSource | null =>
  sources[SUMMON_CLASSES_BLOCK]?.[bodyClassHash] ?? null;
